package akun;


import java.awt.FlowLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author asus
 */
public class DashboardFrame extends javax.swing.JFrame {
    private double saldo;

    public DashboardFrame() {
        // Set judul frame
        setTitle("Dashboard Aplikasi Pengatur Keuangan Mahasiswa");

        // Set ukuran frame
        setSize(400, 200);

        // Set layout manager
        setLayout(new FlowLayout());

        // Inisialisasi saldo awal
        saldo = 0;

        // Tambahkan komponen ke frame
        JLabel saldoLabel = new JLabel("Saldo Anda: Rp" + saldo);
        add(saldoLabel);

        JTextField setoranField = new JTextField(10);
        add(new JLabel("Setor Uang:"));
        add(setoranField);

        JTextField penarikanField = new JTextField(10);
        add(new JLabel("Tarik Uang:"));
        add(penarikanField);

        // Tambahkan JComboBox untuk memilih kategori tarik uang
        String[] kategori = {"Makanan", "Transportasi", "Pendidikan", "Lainnya"};
        JComboBox<String> kategoriComboBox = new JComboBox<>(kategori);
        add(new JLabel("Kategori:"));
        add(kategoriComboBox);

        JButton setorButton = new JButton("Setor");
        add(setorButton);

        JButton tarikButton = new JButton("Tarik");
        add(tarikButton);

        JButton keluarButton = new JButton("Keluar");
        add(keluarButton);

        // Tambahkan action listener untuk setorButton
        setorButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                double setoran = Double.parseDouble(setoranField.getText());
                saldo += setoran;
                saldoLabel.setText("Saldo Anda: Rp" + saldo);
            }
        });

        // Tambahkan action listener untuk tarikButton
        tarikButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                double penarikan = Double.parseDouble(penarikanField.getText());
                String kategoriTarik = (String) kategoriComboBox.getSelectedItem();
                saldo -= penarikan;
                saldoLabel.setText("Saldo Anda: Rp" + saldo);
                // Menampilkan pesan dialog untuk kategori tarik uang
                JOptionPane.showMessageDialog(DashboardFrame.this,
                        "Anda melakukan penarikan sebesar Rp" + penarikan + " dari kategori: " + kategoriTarik,
                        "Penarikan Uang", JOptionPane.INFORMATION_MESSAGE);
            }
        });

        // Tambahkan action listener untuk keluarButton
        keluarButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                saldo = 0;
                // Tampilkan dialog pesan sebelum keluar
                JOptionPane.showMessageDialog(DashboardFrame.this,
                        "Terima kasih telah menggunakan aplikasi pengatur keuangan mahasiswa!",
                        "Keluar", JOptionPane.INFORMATION_MESSAGE);
                // Tutup frame
                dispose();
            }
        });

        // Set visible
        setVisible(true);

        // Set default close operation
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }

    /**
     * Creates new form DashboardFrame
     */
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("saldo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(jLabel1)
                .addContainerGap(216, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 255, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
       public static void main(String[] args) {
        // Jalankan frame dalam event dispatch thread
        SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                new DashboardFrame();
            }
        });
        }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
